package com.claurier.MonAquedi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UniteMesure generated by hbm2java
 */
@Entity
@Table(name = "unite_mesure", schema = "sandre"
)
@Inheritance(strategy= InheritanceType.JOINED)
@JsonPropertyOrder(value = {"CdUniteMesure", "CdUniteMesureSchemeAgencyId"}, alphabetic = true)
public class UniteMesure implements java.io.Serializable {

    private Integer UniteMesureId;
    private String CdUniteMesure;
    private String CdUniteMesureSchemeAgencyId;
    private String LbUniteMesure;
    private String SymUniteMesure;
    private String StUniteMesure;
    private String StUniteMesureListAgencyId;
    private Date DateCreUniteMesure;
    private Date DateMajUniteMesure;
    private String DsUniteMesure;
    private String AuteurUniteMesure;
    private String RefUniteMesure;
    private String NomIntUniteMesure;
    private Boolean isPivot = false;

    public UniteMesure() {
    }

    public UniteMesure(@JsonProperty("CdUniteMesure") String CdUniteMesure, @JsonProperty("CdUniteMesureSchemeAgencyId") String CdUniteMesureSchemeAgencyId) {
        this.CdUniteMesure = CdUniteMesure;
        this.CdUniteMesureSchemeAgencyId = CdUniteMesureSchemeAgencyId;
    }

    public UniteMesure(String CdUniteMesure, String CdUniteMesureSchemeAgencyId, String LbUniteMesure, String SymUniteMesure, String StUniteMesure, String StUniteMesureListAgencyId, Date DateCreUniteMesure, Date DateMajUniteMesure, String DsUniteMesure, String AuteurUniteMesure, String RefUniteMesure, String NomIntUniteMesure, Boolean isPivot

    ) {
        this.CdUniteMesure = CdUniteMesure;
        this.CdUniteMesureSchemeAgencyId = CdUniteMesureSchemeAgencyId;
        this.LbUniteMesure = LbUniteMesure;
        this.SymUniteMesure = SymUniteMesure;
        this.StUniteMesure = StUniteMesure;
        this.StUniteMesureListAgencyId = StUniteMesureListAgencyId;
        this.DateCreUniteMesure = DateCreUniteMesure;
        this.DateMajUniteMesure = DateMajUniteMesure;
        this.DsUniteMesure = DsUniteMesure;
        this.AuteurUniteMesure = AuteurUniteMesure;
        this.RefUniteMesure = RefUniteMesure;
        this.NomIntUniteMesure = NomIntUniteMesure;
        this.isPivot = isPivot;
    }

    @SequenceGenerator(name = "generator_unite_mesure", sequenceName = "test.unite_mesure_unite_mesure_id_seq", allocationSize=1)
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "unite_mesure_id", unique = true, nullable = false)
    //@JsonIgnore
    public Integer getUniteMesureId() {
        return this.UniteMesureId;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + Objects.hashCode(this.getCdUniteMesure());
        hash = 67 * hash + Objects.hashCode(this.getCdUniteMesureSchemeAgencyId());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (! (obj instanceof UniteMesure) ) {
            return false;
        }
        final UniteMesure other = (UniteMesure) obj;
        if (!Objects.equals(this.getCdUniteMesure(), other.getCdUniteMesure())) {
            return false;
        }
        if (!Objects.equals(this.getCdUniteMesureSchemeAgencyId(), other.getCdUniteMesureSchemeAgencyId())) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Unité de Mesure "+ ((null == this.CdUniteMesure || this.CdUniteMesure.isEmpty())?"non-définie":this.CdUniteMesure) ;
    }

    public void setUniteMesureId(Integer UniteMesureId) {
        this.UniteMesureId = UniteMesureId;
    }

    @Column(name = "cd_unite_mesure")
    public String getCdUniteMesure() {
        return this.CdUniteMesure;
    }

    public void setCdUniteMesure(String CdUniteMesure) {
        this.CdUniteMesure = CdUniteMesure;
    }

    @Column(name = "cd_unite_mesure_scheme_agency_id")
    public String getCdUniteMesureSchemeAgencyId() {
        return this.CdUniteMesureSchemeAgencyId;
    }

    public void setCdUniteMesureSchemeAgencyId(String CdUniteMesureSchemeAgencyId) {
        this.CdUniteMesureSchemeAgencyId = CdUniteMesureSchemeAgencyId;
    }

    @Column(name = "lb_unite_mesure")
    public String getLbUniteMesure() {
        return this.LbUniteMesure;
    }

    public void setLbUniteMesure(String LbUniteMesure) {
        this.LbUniteMesure = LbUniteMesure;
    }

    @Column(name = "sym_unite_mesure")
    public String getSymUniteMesure() {
        return this.SymUniteMesure;
    }

    public void setSymUniteMesure(String SymUniteMesure) {
        this.SymUniteMesure = SymUniteMesure;
    }

    @Column(name = "st_unite_mesure")
    public String getStUniteMesure() {
        return this.StUniteMesure;
    }

    public void setStUniteMesure(String StUniteMesure) {
        this.StUniteMesure = StUniteMesure;
    }

    @Column(name = "st_unite_mesure_list_agency_id")
    public String getStUniteMesureListAgencyId() {
        return this.StUniteMesureListAgencyId;
    }

    public void setStUniteMesureListAgencyId(String StUniteMesureListAgencyId) {
        this.StUniteMesureListAgencyId = StUniteMesureListAgencyId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_cre_unite_mesure", length = 13)
    public Date getDateCreUniteMesure() {
        return this.DateCreUniteMesure;
    }

    public void setDateCreUniteMesure(Date DateCreUniteMesure) {
        this.DateCreUniteMesure = DateCreUniteMesure;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_maj_unite_mesure", length = 29)
    public Date getDateMajUniteMesure() {
        return this.DateMajUniteMesure;
    }

    public void setDateMajUniteMesure(Date DateMajUniteMesure) {
        this.DateMajUniteMesure = DateMajUniteMesure;
    }

    @Column(name = "ds_unite_mesure")
    public String getDsUniteMesure() {
        return this.DsUniteMesure;
    }

    public void setDsUniteMesure(String DsUniteMesure) {
        this.DsUniteMesure = DsUniteMesure;
    }

    @Column(name = "auteur_unite_mesure")
    public String getAuteurUniteMesure() {
        return this.AuteurUniteMesure;
    }

    public void setAuteurUniteMesure(String AuteurUniteMesure) {
        this.AuteurUniteMesure = AuteurUniteMesure;
    }

    @Column(name = "ref_unite_mesure")
    public String getRefUniteMesure() {
        return this.RefUniteMesure;
    }

    public void setRefUniteMesure(String RefUniteMesure) {
        this.RefUniteMesure = RefUniteMesure;
    }

    @Column(name = "nom_int_unite_mesure")
    public String getNomIntUniteMesure() {
        return this.NomIntUniteMesure;
    }

    public void setNomIntUniteMesure(String NomIntUniteMesure) {
        this.NomIntUniteMesure = NomIntUniteMesure;
    }

    @Column(name = "flag_pivot", columnDefinition="boolean default false", nullable = false)
    public Boolean getPivot() {
        return isPivot;
    }

    public void setPivot(Boolean pivot) {
        isPivot = pivot;
    }

}

